// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUUGquKGCWXteSJoU8l3FsGerfmWLm470',
    appId: '1:306834710746:web:488c5a88dfd8a9a8cf05e3',
    messagingSenderId: '306834710746',
    projectId: 'prakflutterfirebase-1c1bc',
    authDomain: 'prakflutterfirebase-1c1bc.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-1c1bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDHHZWpuTZ4yNr0vQns7n656liUAgRUVY',
    appId: '1:306834710746:android:786562f1b9a6a5dacf05e3',
    messagingSenderId: '306834710746',
    projectId: 'prakflutterfirebase-1c1bc',
    storageBucket: 'prakflutterfirebase-1c1bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUaSr5D1JH9a2RrxJCLqvu3gb3LDgwPxI',
    appId: '1:306834710746:ios:05e6cffa6d82fca6cf05e3',
    messagingSenderId: '306834710746',
    projectId: 'prakflutterfirebase-1c1bc',
    storageBucket: 'prakflutterfirebase-1c1bc.appspot.com',
    androidClientId:
        '306834710746-pncad301iktn3uemss2ffjp2ao868vfj.apps.googleusercontent.com',
    iosClientId:
        '306834710746-kpv057jtad83kfqtaua556r7dldpdcgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikumFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUaSr5D1JH9a2RrxJCLqvu3gb3LDgwPxI',
    appId: '1:306834710746:ios:05e6cffa6d82fca6cf05e3',
    messagingSenderId: '306834710746',
    projectId: 'prakflutterfirebase-1c1bc',
    storageBucket: 'prakflutterfirebase-1c1bc.appspot.com',
    androidClientId:
        '306834710746-pncad301iktn3uemss2ffjp2ao868vfj.apps.googleusercontent.com',
    iosClientId:
        '306834710746-kpv057jtad83kfqtaua556r7dldpdcgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikumFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUUGquKGCWXteSJoU8l3FsGerfmWLm470',
    appId: '1:306834710746:web:1e4494e27c8ce190cf05e3',
    messagingSenderId: '306834710746',
    projectId: 'prakflutterfirebase-1c1bc',
    authDomain: 'prakflutterfirebase-1c1bc.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-1c1bc.appspot.com',
  );
}
